version: '3.8'

services:
  rails-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - AWS_REGION=us-east-1  # Change to your AWS region
    # depends_on:
    #   - otel-collector

  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   ports:
  #     - "4317:4317" # OTLP gRPC
  #     - "4318:4318" # OTLP HTTP
