# PostgresDB
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: myuser
  password: mypassword
  host: localhost

development:
  <<: *default
  database: otel_rails_dev

production:
  <<: *default
  database: otel_rails_prod
  username: myuser
  password: mypassword
